---
- name: Install epel-release
  yum: name=epel-release state=present

- name: Install Nginx web server
  yum: name=nginx state=present

- name: Copy index.html
  copy: src=files/index.html dest=/usr/share/nginx/html/ mode=0644

