---
- hosts: git
  vars:
    gitea_version: 1.3.2
    git_url: http://git.kappa
  tasks:
    - name: Install requirement packages
      yum: name={{ item }} state=installed update_cache=yes
      with_items:
        - wget
        - git
        - epel-release

    - name: Create user
      user: name=git state=present

    - name: Install Gitea
      get_url: url=https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64 dest=/home/git/gitea mode=0744 owner=git

    - name: Copy systemd unit file
      copy: src=files/gitea.service dest=/etc/systemd/system/gitea.service

    - name: Start Gitea service
      systemd: name=gitea.service state=started enabled=yes

    - name: Install Nginx
      yum: name=nginx state=installed update_cache=yes

    - name: Copy Nginx config
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

    - name: Start Nginx service
      systemd: name=nginx.service state=started enabled=yes
