---

- name: "Provision Debian configuration"
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  roles:
    - {role: "update",      tags: "update"}
    - {role: "system",      tags: "system"}
    - {role: "user",        tags: "user"}
    - {role: "packages",    tags: "packages"}
    - {role: "flatpak",     tags: "flatpak"}
    - {role: "gnome",       tags: "gnome"}
    - {role: "dotfiles",    tags: "dotfiles"}
    - {role: "development", tags: "development"}
  vars:
    ansible_become: true
    system:
      hostname: "debian"
      timezone: "Europe/Kyiv"
    user:
      name: "msytnyk"
      groups: 
        - "sudo"
    packages:
      skip_install: true
      skip_remove: false
      install:
        - "git"
        - "vim"
        - "tmux"
        - "wget"
        - "flatpak"
        - "dconf-editor"
        - "podman"
        - "podman-compose"
        - "starship"
        - "distrobox"
        - "python3-pip"
        - "python3-apt"
        - "python3-venv"
        - "pulseaudio-utils"
        - "pavucontrol"
        - "7zip"
        - "file-roller"
        - "shotwell"
        - "zsh"
        - "gnome-shell-extension-appindicator"
        - "gnome-shell-extension-autohidetopbar"
        - "gnome-shell-extension-blur-my-shell"
        - "gnome-shell-extension-gpaste"
        - "gnome-shell-extension-just-perfection"
        - "gnome-shell-extension-gsconnect"
        - "gnome-shell-extension-light-style"
        #- "qemu/libvirt/virt-manager"

      remove:
        - "fcitx5"
        - "goldendict-ng"
        - "libreoffice*"
        - "anthy"
        - "xiterm*"
        - "*mozc*"
        - "gnome-tour"
        - "thunderbird"
        #- "evolution"  # removes gnome
        #- "gnome-contacts"
    flatpak:
      skip_install: true
      skip_remove: true
      install:
        - "app.zen_browser.zen"
        - "com.github.tchx84.Flatseal"
        - "com.mattjakeman.ExtensionManager"
        - "page.tesk.Refine"
        - "dev.zed.Zed"
        - "app.devsuite.Ptyxis"
        - "io.bassi.Amberol"
      remove: []
