---

- name: "Provision Debian configuration"
  hosts: "localhost"
  connection: "local"
  gather_facts: false
  roles:
    - {role: "update",      tags: "update", become: true }
    - {role: "packages",    tags: "packages", become: true }
    - {role: "system",      tags: "system", become: true }
    - {role: "user",        tags: "user", become: true }
    - {role: "flatpak",     tags: "flatpak", become: false }
    - {role: "gnome",       tags: "gnome", become: false }
    - {role: "dotfiles",    tags: "dotfiles", become: false }
    - {role: "development", tags: "development", become: false }
  vars:
    # ansible_become: true
    update:
      enabled: true
    system:
      hostname: "debian"
      timezone: "Europe/Kyiv"
    user:
      name: "msytnyk"
      groups:
        - "sudo"
        - "keyd"
        - "kvm"
        - "libvirt"
    packages:
      enabled:
        install: true
        remove: true
      install:
        - "git"
        - "vim"
        - "tmux"
        - "wget"
        - "flatpak"
        - "dconf-editor"
        - "podman"
        - "podman-compose"
        - "starship"
        - "distrobox"
        - "python3-pip"
        - "python3-apt"
        - "python3-venv"
        - "python3-psutil"
        - "pulseaudio-utils"
        - "pavucontrol"
        - "7zip"
        - "file-roller"
        - "shotwell"
        - "zsh"
        - "zsh-autosuggestions"
        - "zsh-syntax-highlighting"
        - "fzf"
        - "gnome-software-plugin-flatpak"
        - "gnome-software-plugin-fwupd"
        - "gnome-shell-extension-appindicator"
        - "gnome-shell-extension-autohidetopbar"
        - "gnome-shell-extension-blur-my-shell"
        - "gnome-shell-extension-gpaste"
        - "gnome-shell-extension-just-perfection"
        - "gnome-shell-extension-gsconnect"
        - "gnome-shell-extension-light-style"
        - "remmina"
        - "remmina-plugin-rdp"
        - "remmina-plugin-vnc"
        - "alacritty"
        - "emacs-pgtk"
        - "emacs-libvterm"
        - "keyd"
        - "qemu-kvm"
        - "libvirt-daemon-system"
        - "libvirt-clients"
        - "bridge-utils"
        - "virt-manager"
        - "pass"
        - "pass-otp"
        - "zbar"
        - "scdaemon"
        - "pcscd"
        - "yubikey-personalization"

      remove:
        - "fcitx5"
        - "goldendict-ng"
        - "libreoffice*"
        - "anthy"
        - "xiterm*"
        - "*mozc*"
        - "gnome-tour"
        - "thunderbird"
        - "fonts-firacode"  # managed by brew
        #- "evolution"  # removes gnome
        #- "gnome-contacts"
    flatpak:
      enabled:
        install: true
        remove: true
      install:
        - "app.zen_browser.zen"
        - "com.github.tchx84.Flatseal"
        - "com.mattjakeman.ExtensionManager"
        - "page.tesk.Refine"
        - "dev.zed.Zed"
        - "io.bassi.Amberol"
        - "com.slack.Slack"
        - "us.zoom.Zoom"
        - "io.dbeaver.DBeaverCommunity"
      remove:
        - "app.devsuite.Ptyxis"
