---
- hosts: stormey
#  connection: local
  tasks:
    - name: Disable SELinux
      selinux: policy=targeted state=permissive
      
    - name: Enable copr LXD
      command: dnf copr enable ganto/lxd -y

    - name: Enable copr LXC 2.1
      command: dnf copr enable ganto/lxc -y

    - name: Install LXD tools
      dnf: name={{item}} state=installed
      with_items:
        - lxd
        - lxd-client
        - lxd-tools

    - name: Add user to lxd group
      user: name=hostmorke groups=lxd append=yes

    - name: Set subuid
      lineinfile: path=/etc/subuid line="root:1000000:65536"

    - name: Set subgid
      lineinfile: path=/etc/subgid line="root:1000000:65536"

    - name: Start LXD service
      systemd: name=lxd.service state=started
