---
- hosts: localhost
  connection: local
  become: true
  vars:
    release: 31
  tasks:
    - name: Disable services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - dnf-makecache
        - firewalld
        - sssd
        - abrtd
        - lvm2-monitor
        - dnfdaemon

    - name: Clean packages
      dnf:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - geany
        - dnfdragora
        - xfburn
        - gnumeric
        - pidgin
        - claws-mail
        - transmission

    - name: Install basic tools
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - vim
        - tmux
        - git
        - podman
        - ansible
        - dnf-plugins-core
        - mozilla-fira-mono-fonts
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ release }}.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ release }}.noarch.rpm
        - https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.rpm

    - name: Install media
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - mpv
        - ffmpeg
        - rtmpdump
        - VirtualBox
