---
- hosts: stormey
  tasks:
    - name: Install vim
      dnf: name=vim state=latest

    - name: Install tmux
      dnf: name=tmux state=latest

    - name: Install git
      dnf: name=git state=latest

    - name: Install Docker
      dnf: name=dnf-plugins-core state=latest
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      dnf: name=docker-ce state=latest

    - name: Install LXD