---
- hosts: localhost
  connection: local
  tasks: 
    - name: Pull Docker images
      docker_image: name={{item}}
      with_items:
        - iaroki/dwmbuild
        - iaroki/irssi
        - iaroki/hugo
        - iaroki/libreoffice
        - iaroki/teamviewer
        - iaroki/transmission
        - iaroki/wireshark
        - iaroki/pelican
        - iaroki/zeal
        - iaroki/chromium
        - iaroki/iriverpla
        - iaroki/sublime
        - iaroki/qwordnotify
        - iaroki/conky
        - iaroki/obs
        - iaroki/popcorntime
        - iaroki/thunderbird
        - iaroki/pass
