---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update system
      xbps: upgrade=yes update_cache=yes

    - name: Install essential tools
      xbps: name={{item}} state=present
      with_items:
        - vim
        - git
        - tree
        - wget  
        - htop
        - scrot
        - tmux
        - gxkb
        - dmenu
        - python3
        - bash-completion
        - void-repo-nonfree
    
    - name: Pull dotfiles
      git: repo=https://github.com/iaroki/dotfiles dest=/home/iaroki/dev

    - name: Install Docker
      xbps: name=docker state=present

    - name: Copy docker config
      copy: src=/home/iaroki/dev/dotfiles/docker/daemon.json dest=/etc/docker/daemon.json remote_src=yes

    - name: Add user to docker group
      user: name=iaroki groups=docker append=yes

    - name: Install VirtualBox
      xbps: name=virtualbox-ose state=present

    - name: Add user to VirtualBox group
      user: name=iaroki groups=vboxusers append=yes

    - name: Install LXC
      xbps: name=lxc state=present

    - name: Copy LXC configs
      copy: src={{item.src}} dest={{item.dest}} remote_src=yes
      with_items:
        - {src: '/home/iaroki/dev/dotfiles/lxc/default.conf', dest: '/etc/lxc/default.conf'}
        - {src: '/home/iaroki/dev/dotfiles/lxc/lxc.conf', dest: '/etc/lxc/lxc.conf'}

    - name: Install Vagrant
      xbps: name=vagrant state=present

    - name: Install media
      xbps: name={{item}} state=present
      with_items:
        - mpv
        - cmus
        - ffmpeg
        - rtmpdump
        - unrar
        
