---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update system
      xbps: upgrade=yes update_cache=yes

    - name: Install essential tools
      xbps: name={{item}} state=present
      with_items:

# Must be preinstalled:
#        - vim
#        - git
#        - python3

        - tree
        - wget  
        - htop
        - scrot
        - tmux
        - gxkb
        - dmenu
        - bash-completion
        - void-repo-nonfree
        - network-manager-applet
    
    - name: Pull dotfiles
      git: repo=https://github.com/iaroki/dotfiles dest=/home/iaroki/dev

    - name: Copy configs
      copy: src={{item.src}} dest={{item.dest}} remote_src=yes
      with_items:
        - {src: '/home/iaroki/dev/dotfiles/.bashrc', dest: '/home/iaroki/.bashrc'}
        - {src: '/home/iaroki/dev/dotfiles/.profile', dest: '/home/iaroki/.profile'}
        - {src: '/home/iaroki/dev/dotfiles/.xinitrc', dest: '/home/iaroki/.xinitrc'}

    - name: Install Docker
      xbps: name=docker state=present

    - name: Copy docker config
      copy: src=/home/iaroki/dev/dotfiles/docker/daemon.json dest=/etc/docker/daemon.json remote_src=yes

    - name: Add user to docker group
      user: name=iaroki groups=docker append=yes
    
    - name: Pull dwm src
      git: repo=https://github.com/iaroki/dwm dest=/home/iaroki/dev

    - name: Build dwm
      shell: build.sh
      args:
        chdir: /home/iaroki/dev/dwm

    - name: Install VirtualBox
      xbps: name=virtualbox-ose state=present

    - name: Add user to VirtualBox group
      user: name=iaroki groups=vboxusers append=yes

    - name: Install LXC
      xbps: name=lxc state=present

    - name: Copy LXC configs
      copy: src={{item.src}} dest={{item.dest}} remote_src=yes
      with_items:
        - {src: '/home/iaroki/dev/dotfiles/lxc/default.conf', dest: '/etc/lxc/default.conf'}
        - {src: '/home/iaroki/dev/dotfiles/lxc/lxc.conf', dest: '/etc/lxc/lxc.conf'}

    - name: Install Vagrant
      xbps: name=vagrant state=present

    - name: Install media
      xbps: name={{item}} state=present
      with_items:
        - mpv
        - cmus
        - ffmpeg
        - rtmpdump
        - unrar
        
