---

all:
  hosts:
    hashistack:
      ansible_host: 10.0.0.226
      ansible_port: 22
      ansible_user: homelab
      ansible_ssh_private_key_file: /Users/msytnyk/.ssh/id_rsa
      ansible_become: true
    # hashistack:
    #   ansible_host: localhost
    #   ansible_port: 2222
    #   ansible_user: vagrant
    #   ansible_ssh_private_key_file: /Users/msytnyk/vagrant/hashistack/.vagrant/machines/default/vmware_desktop/private_key
    #   ansible_become: true
