---
- hosts: kubernetes
  tasks:

    - name: Update system
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Create kubernetes sysctl.conf
      file:
        path: /etc/sysctl.d/kubernetes.conf
        state: touch
        mode: 0644

    - name: Set net.bridge.bridge-nf-call-iptables to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        sysctl_file: /etc/sysctl.d/kubernetes.conf
        sysctl_set: yes
        reload: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add kubernetes repo
      yum_repository:
        name: kubernetes
        description: kubernetes repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

    - name: Install kubernetes
      yum:
        name: kubelet, kubeadm, kubectl
        state: present
        update_cache: yes
        disable_gpg_check: yes

    - name: Start kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
