---
- name: Clone dotfiles
  git: repo='https://github.com/iaroki/dotfiles.git' dest='~/cfg'

- name: Copy .vimrc
  copy: src='~/cfg/.vimrc' dest='~/.vimrc'

- name: Copy .vim dir
  copy: src='~/cfg/.vim' dest='~/'

- name: Copy fonts
  copy: src='~/cfg/.fonts' dest='~/'

