---
- hosts: pelican
  vars:
    blog_author: kappa
    blog_name: Kappa's blog
    blog_url: http://blog.kappa
    blog_path: /var/www/blog/
    blog_content: /var/www/blog/content/
    blog_output: /var/www/blog/output/
  tasks:
    
    - name: Enable EPEL repo
      yum: name=epel-release state=installed

    - name: Install Python 3 and PIP
      yum: name={{ item }} state=installed update_cache=yes
      with_items:
        - python34
        - python34-pip

    - name: Install Pelican with PIP
      pip: name={{ item }} state=present executable=pip3
      with_items:
        - pelican
        - markdown

    - name: Create blog directories
      file: path={{ item }} state=directory mode=0755
      with_items:
        - "{{ blog_path }}"
        - "{{ blog_content }}"
        - "{{ blog_output }}"

    - name: Copy Pelican configs
      template: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: 'pelicanconf.py.j2', dest: '"{{ blog_path }}"/pelicanconf.py' }
        - { src: 'publishconf.py.j2', dest: '"{{ blog_path }}"/publishconf.py' }

    - name: Copy test article
      copy: src=files/first-post.md dest={{ blog_content }}/first-post.md

    - name: Generate static pages
      shell: pelican content
      args:
        chdir: "{{ blog_path }}"

    - name: Install Nginx
      yum: name=nginx state=installed

    - name: Copy nginx.conf
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

    - name: Start and enable Nginx
      systemd: name=nginx state=started enabled=yes

