---
- hosts: centos
  tasks:

    - name: Install Zabbix repo
      yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm state=installed update_cache=yes

    - name: Install Zabbix Agent
      yum: name=zabbix-agent state=installed update_cache=yes

    - name: Start Zabbix service
      systemd: name=zabbix-agent state=started enabled=yes
