---
- hosts: dns
  vars:
    zone_file: kappa.zone
  tasks:

    - name: Install BIND
      yum: name={{ item }} state=installed
      with_items:
        - bind
        - bind-utils

    - name: Copy named.conf
      template: src=named.conf.j2 dest=/etc/named.conf

    - name: Copy ZONE file
      template: src={{ zone_file }}.j2 dest=/var/named/{{ zone_file }}

    - name: Start and enable BIND
      systemd: name=named state=started enabled=yes
