---
- hosts: dns
  tasks:

    - name: Install BIND
      yum: name={{ item }} state=installed
      with_items:
        - bind
        - bind-utils

    - name: Copy named.conf
      template: src=named.conf.j2 dest=/etc/named/named.conf

    - name: Copy ZONE file
      template: src=kappa.zone.j2 dest=/var/named/kappa.zone

    - name: Start and enable BIND
      systemd: name=named state=started enabled=yes
