---

- name: Install Wireguard
  apt:
    name: wireguard
    state: present

- name: Generate Wireguard keys
  shell:
    cmd: |
      umask 077
      wg genkey | tee privatekey | wg pubkey > publickey
    chdir: /etc/wireguard
    creates: privatekey

- name: Register Wireguard private key
  shell:
    cmd: cat /etc/wireguard/privatekey
  register: server_private_key.stdout
  ignore_errors: true

- name: Copy Wireguard config file
  template:
    src: templates/wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart Wireguard service

- name: Start Wireguard service
  systemd:
    name: wg-quick@wg0
    state: started
    enabled: yes
